### PR TITLE
Fix deprecations of isexecutable/isreadable

### PR DESCRIPTION
**Pull request by ScottPJones**
This fixes the deprecations in 0.5, and also makes the files match the Julia standards (i.e. no tabs, no trailing spaces) for code formatting.

### CODE REVIEW

**Comment by aviks** [comment]
Thanks!. But could you please separate the formatting fixes into a separate PR? It is impossible to trace changes in the future otherwise.

**Comment by ScottPJones** [comment]
Sure, sorry, I'll separate those out!

**Comment by ScottPJones** [comment]
OK, now is just the real change, not the untabify + trailing space removals

**Comment by aviks** [comment]
Thanks. I am happy to take the format changes as a separate PR.

**Comment by ScottPJones** [comment]
Will do (after celebrating New Year's, and more importantly, recovering from it! 😄). Happy NY!

**Pull request merged**
