### PR TITLE
avoid double free bug

### PR DESCRIPTION
**Pull request by adambrewster**
convert{T,S}(::Type{JavaObject{T}}, obj::JavaObject{S}) creates a new JavaObject wrapping the same pointer.  Both have finalizers which call DeleteLocalRef.  This changes the convert method to return a JavaObject wrapping a new reference to the same object.

Unfortunately I don't have a simplified to contribute, this is a real bug that I've seen on real code.

May be related to #20.

### CODE REVIEW

**Comment by aviks** [comment]
Thanks, this was clearly a major bug. I want to think about how to write a testcase for this. So I'll sleep on it before merging.

**Comment by adambrewster** [comment]
For what it's worth, I found the problem by keeping a Set{Ptr{Void}} of allocated objects.  In JavaObject I added `@assert ptr ∉ allocated; push!(allocated, ptr)`, and in deleteref, I added `@assert ptr ∈ allocated; delete!(allocated, ptr)`.   I don't think you'd want to do that all the time though, and I don't know a good way this into a proper unit test without keeping two entirely different versions of the code.

**Comment by dfdx** [comment]
I see that it fixes all the issues I described in #20, practically making it possible to move that project further. Can we have this merged.

**Comment by aviks** [comment]
I've added test for this behaviour in https://github.com/aviks/JavaCall.jl/pull/34/commits/99a5c595b4d5ff81f2666af7e463734170b4b5b2

It confirms that JavaCall segfaults reliably without this fix.  Thanks a ton, @adambrewster  for the fix!

**Pull request merged**
