### PR TITLE
Explicit converters for Arrays

### PR DESCRIPTION
**Pull request by dfdx**
`convert()` method for recursive conversion of array objects. Example: 

    obj = ...        # JObject, storing reference to byte[][]
    arr = convert(Array{Array{jbyte, 1}, 1}, obj)  # Julia's Array{Array{jbyte, 1}, 1} with the same data

See [this comment](https://github.com/aviks/JavaCall.jl/issues/13#issuecomment-127078367) for one of the possible use cases for this converter.

### CODE REVIEW

**Comment by aviks** [comment]
This looks OK. I'd like to think this over a little bit, particularly in relation to #13 . I'll merge in a day or two.

**Comment by aviks** [comment]
Could you also add some tests please?

**Comment by dfdx** [comment]
Added some tests. 

> This looks OK. I'd like to think this over a little bit, particularly in relation to #13 . I'll merge in a day or two.

Don't hurry up - these conversions aren't easy to design well, so better to think more now and break less in the future.

**Comment by dfdx** [comment]
Have you come to any decisions regarding such conversions? Now when I'm back to Sparta.jl, it becomes a kind of blocker for me, so some sort of vision would be very helpful.

**Comment by aviks** [comment]
I think the changes in this PR are required, irrespective of what we do about #13

**Comment by dfdx** [comment]
Hmm, did you meant to merge it instead of closing?

**Comment by aviks** [comment]
Duh.. That button!

This needs rebasing... Will get to it once I'm back at a computer.

**Comment by dfdx** [comment]
No problem, I've rebased it onto latest master. I see tests for Julia 0.5 are failing, but I guess it's not a problem at the moment.

**Comment by dfdx** [comment]
Just a kindly reminder about this PR :)

**Comment by aviks** [comment]
Thanks for the reminder... I've been on the road constantly.

**Pull request merged**
